env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
archives:
- format_overrides:
    - goos: windows
      format: zip
brews:
  -
    github:
      owner: syntaqx
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/syntaqx/swarm-api
    description: swarm-api is a dead simple REST API for Docker Swarm
    test: |
      system "#{bin}/swarm-api --version"
snapcrafts:
  -
    publish: true
    grade: stable
    summary: A dead simple rest api for docker swarm
    description: |
      A dead simple REST API for Docker Swarm.
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
